### ISSUE TITLE
Bulk Add using Chapter mode doesn't match identical Chapter titles

### ISSUE THREAD

**Issue by lightmaster** [danrahn/MarkerEditorForPlex#19] opened 2024-02-04 13:15 UTC
**Describe the bug**
Bulk Chapter Add doesn't use matching chapter names. Almost all of the episodes in 1 season have a total of 13 chapters all named "Chapter 1", "Chapter 2", etc. If I select one of the episodes and try to bulk add a Credits marker for Chapter 12 - Chapter 12, the other episodes turn yellow and say that "No matching chapter found, using chapter with closest timestamp", which picks the wrong chapter the vast majority of the time.

**To Reproduce**
0. Have Chapters titled "Chapter 1", "Chapter 2", etc
1. Click on Bulk Add
2. Set to Chapter Mode
3. Set start and stop for 2nd to last chapter
4. See that the majority of other episodes are highlighted yellow for "No Matching Chapter Found", and some are not highlighted for "Start Time is greater than End Time"

**Expected behavior**
If Chapter 12 - Chapter 12 is selected, then it should match Chapter 12 in all selected episodes, regardless of the timestamp of the markers

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: git clone as of 2024-02-03

**Additional context**

**Comment by danrahn** [comment] 2024-02-04 18:34
The issue is likely that the chapters aren't actually titled "Chapter 1", "Chapter 2", etc., but they're unnamed (or at least Plex's database sees them as unnamed) and are just using the default "Chapter X" naming. Since the chapters have no names, the editor will default to finding the chapter that has the closest timestamp match, not necessarily the chapter with the same index. This logic was used because not all episodes in a season will have the same number of chapters, but they are generally the same length, so a timestamp match is more likely to do the right thing.

I'll look into adding a way to override that behavior (i.e. if there's not a named chapter match, use the chapter index instead of the closest timestamp).

**Comment by danrahn** [comment] 2024-02-04 20:27
@lightmaster - a tentative fix has been made with this commit: https://github.com/danrahn/MarkerEditorForPlex/commit/074f5c6b5b0bae650ec63df73484d9579e8f03eb

It might take some time for it to make it to an official release, but hopefully no later than next weekend.



<details>
<summary>Expand for screenshot</summary>

![image](https://github.com/danrahn/MarkerEditorForPlex/assets/7410989/6a411396-5e23-466c-b887-2f71e0e42cd9)

</details>

**Comment by lightmaster** [comment] 2024-02-05 23:37
Opening up all of the files in one of the seasons in MKVToolNix shows that the chapters actually are titled "Chapter 1", "Chapter 2", etc.

Specifically, Episodes 2, 4, and 5 all have 13 chapters that are titled like this. If I select Bulk Add, then set the baseline to episode 2 and tell it to add Credits for Chapter 13 - Chapter 13, Episode 4 turns yellow for no matching chapter title but it can use the closest matching chapter by timestamps, and Episode 5 fails entirely for Start time is greater than end time.

![image](https://github.com/danrahn/MarkerEditorForPlex/assets/5307827/08a99d15-8ad6-4418-8d17-924743a23ec2)
![image](https://github.com/danrahn/MarkerEditorForPlex/assets/5307827/045a6ce7-e52b-4eaf-a5ac-e2ca8a132d6c)
![image](https://github.com/danrahn/MarkerEditorForPlex/assets/5307827/2e992e35-d4e4-4c34-8583-4023bf1ab5a4)

**Comment by lightmaster** [comment] 2024-02-05 23:41
Also, that's before pulling the referenced commit. About to pull new commits and try it again.

**Comment by lightmaster** [comment] 2024-02-06 00:02
Activating TMI logging shows that MarkerEditor isn't finding the chapter titles even though MKVToolNix can:

```
  '134476': [                                                                                                                                                                                                     
    { name: '', index: 0, start: 0, end: 334249 },                                                                                                                                                                
    { name: '', index: 1, start: 334250, end: 705954 },                                                                                                                                                           
    { name: '', index: 2, start: 705955, end: 942106 },                                                                                                                                                           
    { name: '', index: 3, start: 942107, end: 1230311 },                                                                                                                                                          
    { name: '', index: 4, start: 1230312, end: 1688644 },                                                                                                                                                         
    { name: '', index: 5, start: 1688645, end: 1968882 },                                                                                                                                                         
    { name: '', index: 6, start: 1968883, end: 2214336 },                                                
    { name: '', index: 7, start: 2214337, end: 2563393 },                                                
    { name: '', index: 8, start: 2563394, end: 2935973 },                                                
    { name: '', index: 9, start: 2935974, end: 3350637 },                                                
    { name: '', index: 10, start: 3350638, end: 3653649 },                                                                                                                                                        
    { name: '', index: 11, start: 3653650, end: 3723885 },                                               
    { name: '', index: 12, start: 3723886, end: 3790016 },                                               
    [length]: 13                                                                                         
  ],                                                                                                     
  '134477': [                                                                                            
    { name: '', index: 0, start: 0, end: 244451 },                                                       
    { name: '', index: 1, start: 244452, end: 480937 },                                                  
    { name: '', index: 2, start: 480938, end: 797253 },                                                  
    { name: '', index: 3, start: 797254, end: 988945 },                                                  
    { name: '', index: 4, start: 988946, end: 1215004 },                                                 
    { name: '', index: 5, start: 1215005, end: 1509048 },                                                
    { name: '', index: 6, start: 1509049, end: 1763886 },                                                
    { name: '', index: 7, start: 1763887, end: 2044875 },                                                
    { name: '', index: 8, start: 2044876, end: 2275772 },                                                
    { name: '', index: 9, start: 2275773, end: 2563268 },                                                
    { name: '', index: 10, start: 2563269, end: 2695483 },                                               
    { name: '', index: 11, start: 2695484, end: 2729600 },                                               
    { name: '', index: 12, start: 2729601, end: 2800800 },                                               
    [length]: 13                                    
  ],                                                
  '134478': [                                       
    { name: '', index: 0, start: 0, end: 318108 },                                                       
    { name: '', index: 1, start: 318109, end: 531988 },                                                  
    { name: '', index: 2, start: 531989, end: 754085 },                                                  
    { name: '', index: 3, start: 754086, end: 953868 },                                                  
    { name: '', index: 4, start: 953869, end: 1260424 },                                                 
    { name: '', index: 5, start: 1260425, end: 1465463 },                                                
    { name: '', index: 6, start: 1465464, end: 1826490 },                                                
    { name: '', index: 7, start: 1826491, end: 2261091 },                                                
    { name: '', index: 8, start: 2261092, end: 2585206 },                                                
    { name: '', index: 9, start: 2585207, end: 2764177 },                                                
    { name: '', index: 10, start: 2764178, end: 2798294 },                                               
    { name: '', index: 11, start: 2798295, end: 2879293 },                                               
    [length]: 12                                    
  ],
```

**Comment by lightmaster** [comment] 2024-02-06 00:09
Also tried renaming the last 2 chapter of Episode 2 to "Next time" and "Credits", and logs still shows `name: ''` for both of those chapters.

**Comment by danrahn** [comment] 2024-02-06 01:01
Unfortunately those chapters likely fall under the "Plex's database sees them as unnamed" category. If the chapters are given default names, Plex "optimizes" them away:

<details>
<summary>Click to expand</summary>

![image](https://github.com/danrahn/MarkerEditorForPlex/assets/7410989/8acc6d1e-0e38-48b1-9541-466a206b8541)

</details>

As soon as a chapter breaks the pattern, Plex adds all the names to the database:

<details>
<summary>Click to expand</summary>

![image](https://github.com/danrahn/MarkerEditorForPlex/assets/7410989/b5932508-b83f-414e-b81d-159d61a75b50)

</details>

As for

> Also tried renaming the last 2 chapter of Episode 2 using MKVToolNix to "Next time" and "Credits", and logs still shows name: '' for both of those chapters.

Did you manually reanalyze the episodes after editing the names?

**Comment by lightmaster** [comment] 2024-02-06 02:32
> Did you manually reanalyze the episodes after editing the names?

No. Didn't think about that Plex needed to see the change before the database would be updated.

Sounds like using indexes is the only way to go when Plex decides to wipe out the chapter names. That does appear to be working just fine. I've gone through a couple seasons so far with it correctly adding markers where I wanted them.

Question though, would it be possible to remember Bulk Add being set to Chapter Mode and Force Index for a session? As in it will keep those on until you close the page/refresh?

**Comment by danrahn** [comment] 2024-02-06 03:59
> Question though, would it be possible to remember Bulk Add being set to Chapter Mode and Force Index for a session? As in it will keep those on until you close the page/refresh?

Definitely. I've added that here: https://github.com/danrahn/MarkerEditorForPlex/commit/a4c21c6c2fac02d06c1d87ca06d670a78ae80506. It might still persist across refreshes depending on the browser, but they'll go away if you close the page.

I should probably apply this to other dialogs/settings, but the quick fix just addresses Bulk Add's chapter mode/chapter index mode.

**Comment by danrahn** [comment] 2024-02-24 20:30
With these changes in the [latest beta](https://github.com/danrahn/MarkerEditorForPlex/releases/tag/v2.6.4-beta), I'll close this out. But definitely let me know if there's anything else surrounding this behavior that's causing issues though.

**Closed by danrahn** 2024-02-24 20:30 UTC
Labels: bug, accepted
